#Makfile:        Makefile for Test Directory
#__author__      = "Nitin Mohan
#__copyright__   = "Copy Right 2018. NM Technologies"

all:
	if [ ! -d "Obj" ]; then ln -s $(OBJ_DIR) $(TST_DIR); fi
	if [ ! -d "lib_py" ]; then ln -s $(LIBPY_DIR) $(TST_DIR); fi
