#Makfile:        Makefile for Test Directory
#__author__      = "Nitin Mohan
#__copyright__   = "Copy Right 2020. NM Technologies"

ACTIONS = mkdirs

all: $(ACTIONS)

mkdirs:
	if [ ! -d "lib_py" ]; then ln -s $(LIBPY_DIR) $(TOOLS_DIR); fi
